"""Table ids should be strings

Revision ID: 3ea8de9eeffb
Revises: cace39b248c4
Create Date: 2024-08-13 23:11:11.375898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ea8de9eeffb'
down_revision: Union[str, None] = 'cace39b248c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('passwords') as batch_op:
        batch_op.alter_column('user_id',
                              existing_type=sa.INTEGER(),
                              type_=sa.String(length=36),
                              existing_nullable=False)
    with op.batch_alter_table('verification_tokens') as batch_op:
        batch_op.alter_column('user_id',
                              existing_type=sa.INTEGER(),
                              type_=sa.String(length=36),
                              existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('passwords') as batch_op:
        batch_op.alter_column('user_id',
                              existing_type=sa.String(length=36),
                              type_=sa.INTEGER(),
                              existing_nullable=False)
    with op.batch_alter_table('verification_tokens') as batch_op:
        batch_op.alter_column('user_id',
                              existing_type=sa.String(length=36),
                              type_=sa.INTEGER(),
                              existing_nullable=False)
    # ### end Alembic commands ###
