"""User language column removed

Revision ID: 59359c9bc9ed
Revises: 20b702f1f761
Create Date: 2024-08-11 22:37:05.136010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59359c9bc9ed'
down_revision: Union[str, None] = '20b702f1f761'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'language')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('language', sa.VARCHAR(length=2), nullable=True))
    # ### end Alembic commands ###
