"""User pending activation status and full_name property

Revision ID: 9b26e4b28f38
Revises: 5372b2e476af
Create Date: 2024-08-13 01:04:06.406227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b26e4b28f38'
down_revision: Union[str, None] = '5372b2e476af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('status',
                              existing_type=sa.VARCHAR(length=24),
                              type_=sa.Enum('active', 'inactive',
                                            'pending_activation'),
                              default='pending_activation',
                              existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('status',
                              existing_type=sa.Enum('active', 'inactive'),
                              default='active',
                              type_=sa.VARCHAR(length=24),
                              existing_nullable=True)
    # ### end Alembic commands ###
