"""Added verified_at column to verification tokens

Revision ID: cace39b248c4
Revises: 9b26e4b28f38
Create Date: 2024-08-13 21:42:11.523188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cace39b248c4'
down_revision: Union[str, None] = '9b26e4b28f38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_tokens', sa.Column('verified_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verification_tokens', 'verified_at')
    # ### end Alembic commands ###
